export { default as settings } from './settings.svg'
export { default as code } from './code.svg'
export { default as jiraLogo } from './jira-logo.svg'
export { default as github } from './github.svg'
export { default as githubLogo } from './github-logo.svg'
export { default as gitlab } from './gitlab.svg'
export { default as gitlabLogo } from './gitlab-logo.svg'
