name: Build
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      TARGET_BROWSER: chrome
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: packages
          retention-days: 30
